const section = [
    {
      id: 1,
      pName: 'W3 project',
      pAuthure: 'Ali Ahmad &nbsp; &bull; &nbsp; Back End Dev &nbsp;&bullet;&nbsp; 2020',
      pPic: 'images/project1.png',
      pText: 'An open source code for every coding language. W3 school is one the most usefull websites.',
      pTechs: ['Html', 'Css', 'JavaScript'],
      pLive: 'https://aliahmad-karimi.github.io/Porfolio.github.io/',
      pSource: 'https://github.com/Aliahmad-karimi/My-Portfolio',
    },
    {
      id: 2,
      pName: 'YouTube',
      pAuthure: 'Ali Ahmad &nbsp; &bull; &nbsp; Back End Dev &nbsp;&bullet;&nbsp; 2020',
      pPic: 'images/project2.png',
      pText: 'This is a sample from Youtube. It is copy and just for the purpose of demo project.',
      pTechs: ['Html', 'Css', 'JavaScript'],
      pLive: 'https://aliahmad-karimi.github.io/Porfolio.github.io/',
      pSource: 'https://github.com/Aliahmad-karimi/My-Portfolio',
    },
    {
      id: 3,
      pName: 'Grid Game',
      pAuthure: 'Ali Ahmad &nbsp; &bull; &nbsp; Back End Dev &nbsp;&bullet;&nbsp; 2020',
      pPic: 'images/project3.png',
      pText: 'This is a sample from A website that teach us how to learn Grid in a game manner.',
      pTechs: ['Html', 'Css', 'JavaScript'],
      pLive: 'https://aliahmad-karimi.github.io/Porfolio.github.io/',
      pSource: 'https://github.com/Aliahmad-karimi/My-Portfolio',
    },
    {
      id: 4,
      pName: 'Flex Box Game',
      pAuthure: 'Ali Ahmad &nbsp; &bull; &nbsp; Back End Dev &nbsp;&bullet;&nbsp; 2020',
      pPic: 'images/project4.png',
      pText: 'This is website that teach flexbox in a game manner. They are just sample for my project.',
      pTechs: ['Html', 'Css', 'JavaScript'],
      pLive: 'https://aliahmad-karimi.github.io/Porfolio.github.io/',
      pSource: 'https://github.com/Aliahmad-karimi/My-Portfolio',
    },
  ];